---
# pip install passlib
#python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.using(rounds=5000).hash(getpass.getpass())"
password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66636262363362333963373435343463663961336563396333376263383066653132306631616131
          3332313164356235626166636338396262653332313737630a343866316235663162343737643838
          35303365636238363866633031383763653632383434383031666433343732393337363061653365
          3564656165663939620a633537343962303237343933323036613864356437636465376535363235
          39653733653663313230356631373533386337356637313537383433333135643761396663343138
          39653365626239356639666537616235333462623039373164356638616263323337393230323333
          35316335666436316562386365323263373634663533666630633138336232353735663339306661
          36333130316633656566363465633939303233313261323233366234303735666437333133343833
          61626465636339646432306164316131316237353234623464343062386431623131
